<?php
//application details
	$apps[$x]['name'] = "Phonebook";
	$apps[$x]['uuid'] = "9f1c7d20-5a4b-4c8e-9d1a-7b2e3f4a5c60";
	$apps[$x]['category'] = "Contacts";
	$apps[$x]['subcategory'] = "";
	$apps[$x]['version'] = "0.1";
	$apps[$x]['license'] = "MIT";
	$apps[$x]['url'] = "https://github.com/andrewdunn358-dev/synphony-phonebook";
	$apps[$x]['description']['en-us'] = "Per-domain shared phonebook served to desk phones as a remote XML directory (Yealink, Grandstream, Fanvil, Snom).";
	$apps[$x]['description']['en-gb'] = "Per-domain shared phonebook served to desk phones as a remote XML directory (Yealink, Grandstream, Fanvil, Snom).";

//permission details
	$y=0;
	$apps[$x]['permissions'][$y]['name'] = "phonebook_view";
	$apps[$x]['permissions'][$y]['menu']['uuid'] = "b2d4f6a8-1c3e-4570-8a9b-0d1e2f3a4b50";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$apps[$x]['permissions'][$y]['groups'][] = "user";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "phonebook_add";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "phonebook_edit";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	$apps[$x]['permissions'][$y]['name'] = "phonebook_delete";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	//manage the per-domain remote-phonebook access credential
	$apps[$x]['permissions'][$y]['name'] = "phonebook_access";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
	$apps[$x]['permissions'][$y]['groups'][] = "admin";
	$y++;
	//superadmin: manage across all domains / global entries
	$apps[$x]['permissions'][$y]['name'] = "phonebook_domain";
	$apps[$x]['permissions'][$y]['groups'][] = "superadmin";

//schema details - contacts
	$y=0;
	$apps[$x]['db'][$y]['table']['name'] = "v_phonebook";
	$apps[$x]['db'][$y]['table']['parent'] = "";
	$z=0;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "phonebook_uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
	$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
	$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
	$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
	$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_name";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['search'] = 'true';
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Contact display name.";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_organization";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['search'] = 'true';
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Optional organisation.";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "phone_number";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['search'] = 'true';
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Primary phone number.";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "phone_number2";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['search'] = 'true';
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Optional second number.";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "extra";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "jsonb";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Optional per-client custom fields (JSON).";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "enabled";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "boolean";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "boolean";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Show/hide this entry.";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_date";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";

//schema details - per-domain access credential
	$y++;
	$apps[$x]['db'][$y]['table']['name'] = "v_phonebook_auth";
	$apps[$x]['db'][$y]['table']['parent'] = "";
	$z=0;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "phonebook_auth_uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
	$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
	$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
	$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
	$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "username";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Remote-phonebook login username.";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "password_hash";
	$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "bcrypt hash of the login password.";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "enabled";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "boolean";
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "boolean";
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enable/disable this credential.";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "insert_date";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
	$z++;
	$apps[$x]['db'][$y]['fields'][$z]['name'] = "update_date";
	$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
	$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
	$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";

?>
